apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-29T12:44:34Z"
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "2235"
  uid: c5feb98b-ade2-4e17-bf35-1f2f2f1284e8
spec:
  clusterIP: 10.103.145.30
  clusterIPs:
  - 10.103.145.30
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
