apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-09-29T12:28:34Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "17581"
  uid: 7e60c356-fa28-42da-9f91-d6d929e83684
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-09-29T12:28:34Z"
    lastUpdateTime: "2022-09-29T12:28:55Z"
    message: ReplicaSet "hasher-58f5cb8fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-09-29T16:28:34Z"
    lastUpdateTime: "2022-09-29T16:28:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
