apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-09-29T12:29:37Z"
  generation: 1
  labels:
    app: webui
  name: webui
  namespace: default
  resourceVersion: "1228"
  uid: 6b05bf6f-7733-4dcb-85f1-bee557811e75
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webui
    spec:
      containers:
      - image: dockercoins/webui:v0.1
        imagePullPolicy: IfNotPresent
        name: webui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-09-29T12:29:52Z"
    lastUpdateTime: "2022-09-29T12:29:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-09-29T12:29:37Z"
    lastUpdateTime: "2022-09-29T12:29:52Z"
    message: ReplicaSet "webui-8475844547" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
