/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public static void main(String[] args) {
        System.out.println("Hola, Mundo");
        Car car = new Car();
        car.license = "AMQ123";
        car.driver = "Andrés Herrera";
        car.passenger = 4;
        car.printDataCar();

        Car car2 = new Car();
        car2.license = "QWE567";
        car2.driver = "Manuel Herrera";
        car2.passenger = 3;
        car2.printDataCar();
    }
}
