/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public static void main(String[] args) {
        System.out.println("Hola, Mundo");
        Car car = new Car("AMQ123", new Account("Andrés Herrera", "AMD123"));
        car.passenger = 4;
        car.printDataCar();

        Car car2 = new Car("QWE567", new Account("Manuel Herrera", "MAN567"));
        car2.passenger = 3;
        car2.printDataCar();
    }
}
